spring.application.name=ai-resume-analyzer
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB